### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by z3r0privacy** [z3r0privacy/EasyKeepassBrowserPlugin#15]
Integration into pages that use react is faulty. This has the following effects

- data entered, but on login click the page empties the fields and says no data entered
   - e.g. #14
- only username is filled in
   - e.g zalando
- only password is filled in
   - e.g. hello-fresh

possible solutions:
- preferred: detect if react, then work with react events if possible
- detect react, wait a little (500-1000ms) and then try to fill fields
   - maybe update the logic by only filling invisible fields after they become visible (#6)

**Comment by sschw** [comment]
You might look at how the react devtools are tracking the events.

https://github.com/facebook/react/tree/devtools-v4-merge

Also detecting react could be done like this: 
`new RegExp("<[^>]+data-react", "i").test(document.getRootNode().documentElement.innerHTML)`
