### ISSUE TITLE
Keepass2Android Integration

### ISSUE THREAD

**Issue by sschw** [z3r0privacy/EasyKeepassBrowserPlugin#5]
The addon is compatible with firefox for android. 

If Keepass2Android would integrate the webserver, it would also work on android with firefox.

Keepass2Android is Open Source
https://github.com/PhilippC/keepass2android/tree/master/src/keepass2android

**Comment by z3r0privacy** [comment]
not in scope

**Comment by sschw** [comment]
Then expand the scope. This could really benefit the user experience on mobile.
